### ISSUE TITLE
Move Keyring to Aura

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Aura#10]
- [x] Add keyring module from `Nickvision.Keyring` (https://github.com/NickvisionApps/Aura/commit/d4a2bbedfb6f3cac2414e044e2630683802bd03f)
- [ ] Store password in systems secrets library if available
    - [ ] Use Libsecret on Linux
    - [x] Use Windows Credential Manager on Windows

**Comment by fsobolev** [comment]
Probably gonna use [this package](https://www.nuget.org/packages/Meziantou.Framework.Win32.CredentialManager/) for storing password on Windows. I don't think it's the problem that the packages wasn't updated in 2 years, if it will work it will work, and there's still an activity in [github repo](https://github.com/meziantou/Meziantou.Framework) so it's not abandoned.
