### ISSUE TITLE
Add SystemDirectories

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Aura#24]
| Name | Linux | Windows |
| --- | --- | --- |
| Path | array of paths from PATH variable | array of paths from PATH variable |
| Config | array of paths from XDG_CONFIG_DIRS variable | exception? |
| Data | array of paths from XDG_DATA_DIRS variable | exception? |

`Path` can be useful for finding binaries in apps that depend on external programs (fpcalc, ffmpeg).
`Data` can be useful for finding specific files that we could place there (gresource is already there, we could try to place gettext files there maybe).

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Aura/releases/tag/2023.9.4
