### ISSUE TITLE
Use NetworkMonitor portal for Aura.NetworkMonitor

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Aura#28]
https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-NetworkMonitor.GetAvailable

This way we will not need to have NetworkManager DBus permission in flatpak.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Aura/releases/tag/2023.9.5
