### ISSUE TITLE
TranslatorCreditsWithoutUrls

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Aura#33]
Currently, all other credits such as `Developers`, `Artists`, etc are split into a dictionary of their names and urls. This is great for WinUI where urls can't be shown like on GNOME and we can just grab the list of names to show. However, for `TranslatorCredits` it's still a single string and causes a weird look when showing translator credits on WinUI as there is now a url attached. 

Could we apply the same API as other credits and make it a `Dictionary<string, Uri>`?

**Comment by fsobolev** [comment]
The problem is translator credits should be translatable, so it should be a string. Do you need a dictionary or just a list of names in WinUI?

**Comment by nlogozzo** [comment]
just names without urls...maybe we can add a get-only property to AppInfo that's `TranslatorCreditsWithoutUrls` that will remove them from the string.
